package domainapp.modules.simple.enumeradores;

public enum TipoService {
Cambio_De_Aceite,
Inspeccion_Remplazo_Filtros,
Revision_frenos,
Revision_llantas,
Ajuste_Suspencion,
Verificacion_Luces,
Analisis_Sistemas_Electricos,
Reparacion_Motor,
Reparacion_Transmision,
Reparacion_Sistema_De_Escape,
Reparacion_Bateria,
Reparacion_Alternador,
Problemas_Combustible,
Problema_Sistema_Climatizacion,
Problema_Sistema_De_Audio,
Problema_Sistema_De_Seguridad,
Alineacion_Y_Balanceo,
Reparacion_Cubiertas
}
